server:
  port: 8085

spring:
  application:
    name: Pagos
  datasource:
    url: jdbc:mysql://localhost:3306/db_anfri_pagos
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  security:
    user:
      name: admin
      password: 12345